"""
Seed data for major world airports.
~340 airports from public sources (OurAirports, Wikipedia).
"""
import logging
from sqlalchemy.orm import Session

from app.core.database import SessionLocal
from app.models.airport import Airport

logger = logging.getLogger(__name__)

AIRPORTS_DATA = [
    # ── North America ──
    {"iata": "ATL", "icao": "KATL", "name": "Hartsfield-Jackson Atlanta Intl", "city": "Atlanta", "country_iso": "USA", "lat": 33.6407, "lon": -84.4277, "elevation_ft": 1026, "airport_type": "large_airport", "pax_annual": 93.7, "runways": 5, "continent": "NA"},
    {"iata": "DFW", "icao": "KDFW", "name": "Dallas/Fort Worth Intl", "city": "Dallas", "country_iso": "USA", "lat": 32.8998, "lon": -97.0403, "elevation_ft": 607, "airport_type": "large_airport", "pax_annual": 73.4, "runways": 7, "continent": "NA"},
    {"iata": "DEN", "icao": "KDEN", "name": "Denver Intl", "city": "Denver", "country_iso": "USA", "lat": 39.8561, "lon": -104.6737, "elevation_ft": 5431, "airport_type": "large_airport", "pax_annual": 69.3, "runways": 6, "continent": "NA"},
    {"iata": "ORD", "icao": "KORD", "name": "O'Hare Intl", "city": "Chicago", "country_iso": "USA", "lat": 41.9742, "lon": -87.9073, "elevation_ft": 672, "airport_type": "large_airport", "pax_annual": 83.2, "runways": 8, "continent": "NA"},
    {"iata": "LAX", "icao": "KLAX", "name": "Los Angeles Intl", "city": "Los Angeles", "country_iso": "USA", "lat": 33.9425, "lon": -118.4081, "elevation_ft": 125, "airport_type": "large_airport", "pax_annual": 88.1, "runways": 4, "continent": "NA"},
    {"iata": "JFK", "icao": "KJFK", "name": "John F. Kennedy Intl", "city": "New York", "country_iso": "USA", "lat": 40.6413, "lon": -73.7781, "elevation_ft": 13, "airport_type": "large_airport", "pax_annual": 62.5, "runways": 4, "continent": "NA"},
    {"iata": "SFO", "icao": "KSFO", "name": "San Francisco Intl", "city": "San Francisco", "country_iso": "USA", "lat": 37.6213, "lon": -122.3790, "elevation_ft": 13, "airport_type": "large_airport", "pax_annual": 57.5, "runways": 4, "continent": "NA"},
    {"iata": "SEA", "icao": "KSEA", "name": "Seattle-Tacoma Intl", "city": "Seattle", "country_iso": "USA", "lat": 47.4502, "lon": -122.3088, "elevation_ft": 433, "airport_type": "large_airport", "pax_annual": 50.6, "runways": 3, "continent": "NA"},
    {"iata": "MIA", "icao": "KMIA", "name": "Miami Intl", "city": "Miami", "country_iso": "USA", "lat": 25.7959, "lon": -80.2870, "elevation_ft": 8, "airport_type": "large_airport", "pax_annual": 52.0, "runways": 4, "continent": "NA"},
    {"iata": "EWR", "icao": "KEWR", "name": "Newark Liberty Intl", "city": "Newark", "country_iso": "USA", "lat": 40.6895, "lon": -74.1745, "elevation_ft": 18, "airport_type": "large_airport", "pax_annual": 46.3, "runways": 3, "continent": "NA"},
    {"iata": "MCO", "icao": "KMCO", "name": "Orlando Intl", "city": "Orlando", "country_iso": "USA", "lat": 28.4312, "lon": -81.3081, "elevation_ft": 96, "airport_type": "large_airport", "pax_annual": 57.8, "runways": 4, "continent": "NA"},
    {"iata": "IAH", "icao": "KIAH", "name": "George Bush Intercontinental", "city": "Houston", "country_iso": "USA", "lat": 29.9902, "lon": -95.3368, "elevation_ft": 97, "airport_type": "large_airport", "pax_annual": 45.3, "runways": 5, "continent": "NA"},
    {"iata": "YYZ", "icao": "CYYZ", "name": "Toronto Pearson Intl", "city": "Toronto", "country_iso": "CAN", "lat": 43.6777, "lon": -79.6248, "elevation_ft": 569, "airport_type": "large_airport", "pax_annual": 50.5, "runways": 5, "continent": "NA"},
    {"iata": "YVR", "icao": "CYVR", "name": "Vancouver Intl", "city": "Vancouver", "country_iso": "CAN", "lat": 49.1947, "lon": -123.1792, "elevation_ft": 14, "airport_type": "large_airport", "pax_annual": 26.4, "runways": 3, "continent": "NA"},
    {"iata": "MEX", "icao": "MMMX", "name": "Mexico City Intl", "city": "Mexico City", "country_iso": "MEX", "lat": 19.4363, "lon": -99.0721, "elevation_ft": 7316, "airport_type": "large_airport", "pax_annual": 52.9, "runways": 2, "continent": "NA"},
    {"iata": "CUN", "icao": "MMUN", "name": "Cancún Intl", "city": "Cancún", "country_iso": "MEX", "lat": 21.0365, "lon": -86.8771, "elevation_ft": 22, "airport_type": "large_airport", "pax_annual": 31.2, "runways": 2, "continent": "NA"},
    # ── North America (additional) ──
    {"iata": "LAS", "icao": "KLAS", "name": "Harry Reid Intl", "city": "Las Vegas", "country_iso": "USA", "lat": 36.0840, "lon": -115.1537, "elevation_ft": 2181, "airport_type": "large_airport", "pax_annual": 57.3, "runways": 4, "continent": "NA"},
    {"iata": "CLT", "icao": "KCLT", "name": "Charlotte Douglas Intl", "city": "Charlotte", "country_iso": "USA", "lat": 35.2140, "lon": -80.9431, "elevation_ft": 748, "airport_type": "large_airport", "pax_annual": 54.2, "runways": 4, "continent": "NA"},
    {"iata": "PHX", "icao": "KPHX", "name": "Phoenix Sky Harbor Intl", "city": "Phoenix", "country_iso": "USA", "lat": 33.4373, "lon": -112.0078, "elevation_ft": 1135, "airport_type": "large_airport", "pax_annual": 53.8, "runways": 3, "continent": "NA"},
    {"iata": "BOS", "icao": "KBOS", "name": "Boston Logan Intl", "city": "Boston", "country_iso": "USA", "lat": 42.3656, "lon": -71.0096, "elevation_ft": 20, "airport_type": "large_airport", "pax_annual": 42.5, "runways": 6, "continent": "NA"},
    {"iata": "MSP", "icao": "KMSP", "name": "Minneapolis-Saint Paul Intl", "city": "Minneapolis", "country_iso": "USA", "lat": 44.8848, "lon": -93.2223, "elevation_ft": 841, "airport_type": "large_airport", "pax_annual": 39.6, "runways": 4, "continent": "NA"},
    {"iata": "FLL", "icao": "KFLL", "name": "Fort Lauderdale-Hollywood Intl", "city": "Fort Lauderdale", "country_iso": "USA", "lat": 26.0726, "lon": -80.1527, "elevation_ft": 9, "airport_type": "large_airport", "pax_annual": 36.7, "runways": 2, "continent": "NA"},
    {"iata": "DTW", "icao": "KDTW", "name": "Detroit Metropolitan Wayne County", "city": "Detroit", "country_iso": "USA", "lat": 42.2124, "lon": -83.3534, "elevation_ft": 645, "airport_type": "large_airport", "pax_annual": 36.4, "runways": 6, "continent": "NA"},
    {"iata": "PHL", "icao": "KPHL", "name": "Philadelphia Intl", "city": "Philadelphia", "country_iso": "USA", "lat": 39.8721, "lon": -75.2411, "elevation_ft": 36, "airport_type": "large_airport", "pax_annual": 33.8, "runways": 4, "continent": "NA"},
    {"iata": "SLC", "icao": "KSLC", "name": "Salt Lake City Intl", "city": "Salt Lake City", "country_iso": "USA", "lat": 40.7884, "lon": -111.9778, "elevation_ft": 4227, "airport_type": "large_airport", "pax_annual": 27.8, "runways": 4, "continent": "NA"},
    {"iata": "IAD", "icao": "KIAD", "name": "Washington Dulles Intl", "city": "Washington", "country_iso": "USA", "lat": 38.9445, "lon": -77.4558, "elevation_ft": 313, "airport_type": "large_airport", "pax_annual": 27.2, "runways": 4, "continent": "NA"},
    {"iata": "BWI", "icao": "KBWI", "name": "Baltimore/Washington Intl", "city": "Baltimore", "country_iso": "USA", "lat": 39.1754, "lon": -76.6684, "elevation_ft": 146, "airport_type": "large_airport", "pax_annual": 27.1, "runways": 3, "continent": "NA"},
    {"iata": "SAN", "icao": "KSAN", "name": "San Diego Intl", "city": "San Diego", "country_iso": "USA", "lat": 32.7336, "lon": -117.1897, "elevation_ft": 17, "airport_type": "large_airport", "pax_annual": 25.6, "runways": 1, "continent": "NA"},
    {"iata": "DCA", "icao": "KDCA", "name": "Ronald Reagan Washington Natl", "city": "Washington", "country_iso": "USA", "lat": 38.8521, "lon": -77.0377, "elevation_ft": 15, "airport_type": "large_airport", "pax_annual": 25.0, "runways": 3, "continent": "NA"},
    {"iata": "TPA", "icao": "KTPA", "name": "Tampa Intl", "city": "Tampa", "country_iso": "USA", "lat": 27.9755, "lon": -82.5332, "elevation_ft": 26, "airport_type": "large_airport", "pax_annual": 23.4, "runways": 3, "continent": "NA"},
    {"iata": "BNA", "icao": "KBNA", "name": "Nashville Intl", "city": "Nashville", "country_iso": "USA", "lat": 36.1263, "lon": -86.6774, "elevation_ft": 599, "airport_type": "large_airport", "pax_annual": 22.0, "runways": 4, "continent": "NA"},
    {"iata": "HNL", "icao": "PHNL", "name": "Daniel K. Inouye Intl", "city": "Honolulu", "country_iso": "USA", "lat": 21.3187, "lon": -157.9225, "elevation_ft": 13, "airport_type": "large_airport", "pax_annual": 21.4, "runways": 4, "continent": "NA"},
    {"iata": "PDX", "icao": "KPDX", "name": "Portland Intl", "city": "Portland", "country_iso": "USA", "lat": 45.5898, "lon": -122.5951, "elevation_ft": 31, "airport_type": "large_airport", "pax_annual": 20.3, "runways": 3, "continent": "NA"},
    {"iata": "AUS", "icao": "KAUS", "name": "Austin-Bergstrom Intl", "city": "Austin", "country_iso": "USA", "lat": 30.1945, "lon": -97.6699, "elevation_ft": 542, "airport_type": "large_airport", "pax_annual": 20.1, "runways": 2, "continent": "NA"},
    {"iata": "GDL", "icao": "MMGL", "name": "Guadalajara Intl", "city": "Guadalajara", "country_iso": "MEX", "lat": 20.5218, "lon": -103.3113, "elevation_ft": 5016, "airport_type": "large_airport", "pax_annual": 15.6, "runways": 2, "continent": "NA"},
    {"iata": "RDU", "icao": "KRDU", "name": "Raleigh-Durham Intl", "city": "Raleigh", "country_iso": "USA", "lat": 35.8776, "lon": -78.7875, "elevation_ft": 435, "airport_type": "large_airport", "pax_annual": 15.2, "runways": 3, "continent": "NA"},
    {"iata": "SJU", "icao": "TJSJ", "name": "Luis Muñoz Marín Intl", "city": "San Juan", "country_iso": "PRI", "lat": 18.4394, "lon": -66.0018, "elevation_ft": 9, "airport_type": "large_airport", "pax_annual": 10.1, "runways": 2, "continent": "NA"},
    {"iata": "YUL", "icao": "CYUL", "name": "Montréal-Trudeau Intl", "city": "Montréal", "country_iso": "CAN", "lat": 45.4706, "lon": -73.7408, "elevation_ft": 118, "airport_type": "large_airport", "pax_annual": 20.3, "runways": 3, "continent": "NA"},
    {"iata": "YYC", "icao": "CYYC", "name": "Calgary Intl", "city": "Calgary", "country_iso": "CAN", "lat": 51.1215, "lon": -114.0076, "elevation_ft": 3557, "airport_type": "large_airport", "pax_annual": 17.7, "runways": 4, "continent": "NA"},
    {"iata": "YEG", "icao": "CYEG", "name": "Edmonton Intl", "city": "Edmonton", "country_iso": "CAN", "lat": 53.3097, "lon": -113.5800, "elevation_ft": 2373, "airport_type": "large_airport", "pax_annual": 8.2, "runways": 2, "continent": "NA"},
    {"iata": "SJO", "icao": "MROC", "name": "Juan Santamaría Intl", "city": "San José", "country_iso": "CRI", "lat": 9.9939, "lon": -84.2088, "elevation_ft": 3021, "airport_type": "large_airport", "pax_annual": 6.8, "runways": 1, "continent": "NA"},
    {"iata": "ANC", "icao": "PANC", "name": "Ted Stevens Anchorage Intl", "city": "Anchorage", "country_iso": "USA", "lat": 61.1743, "lon": -149.9962, "elevation_ft": 152, "airport_type": "large_airport", "pax_annual": 5.3, "runways": 3, "continent": "NA"},
    {"iata": "YOW", "icao": "CYOW", "name": "Ottawa Macdonald-Cartier Intl", "city": "Ottawa", "country_iso": "CAN", "lat": 45.3225, "lon": -75.6692, "elevation_ft": 374, "airport_type": "large_airport", "pax_annual": 5.1, "runways": 3, "continent": "NA"},

    # ── Europe ──
    {"iata": "LHR", "icao": "EGLL", "name": "London Heathrow", "city": "London", "country_iso": "GBR", "lat": 51.4700, "lon": -0.4543, "elevation_ft": 83, "airport_type": "large_airport", "pax_annual": 79.2, "runways": 2, "continent": "EU"},
    {"iata": "CDG", "icao": "LFPG", "name": "Paris Charles de Gaulle", "city": "Paris", "country_iso": "FRA", "lat": 49.0097, "lon": 2.5479, "elevation_ft": 392, "airport_type": "large_airport", "pax_annual": 76.2, "runways": 4, "continent": "EU"},
    {"iata": "IST", "icao": "LTFM", "name": "Istanbul Airport", "city": "Istanbul", "country_iso": "TUR", "lat": 41.2753, "lon": 28.7519, "elevation_ft": 325, "airport_type": "large_airport", "pax_annual": 76.0, "runways": 5, "continent": "EU"},
    {"iata": "AMS", "icao": "EHAM", "name": "Amsterdam Schiphol", "city": "Amsterdam", "country_iso": "NLD", "lat": 52.3105, "lon": 4.7683, "elevation_ft": -11, "airport_type": "large_airport", "pax_annual": 71.7, "runways": 6, "continent": "EU"},
    {"iata": "FRA", "icao": "EDDF", "name": "Frankfurt Airport", "city": "Frankfurt", "country_iso": "DEU", "lat": 50.0379, "lon": 8.5622, "elevation_ft": 364, "airport_type": "large_airport", "pax_annual": 69.4, "runways": 4, "continent": "EU"},
    {"iata": "MAD", "icao": "LEMD", "name": "Madrid Barajas", "city": "Madrid", "country_iso": "ESP", "lat": 40.4719, "lon": -3.5626, "elevation_ft": 1998, "airport_type": "large_airport", "pax_annual": 60.2, "runways": 4, "continent": "EU"},
    {"iata": "BCN", "icao": "LEBL", "name": "Barcelona El Prat", "city": "Barcelona", "country_iso": "ESP", "lat": 41.2974, "lon": 2.0833, "elevation_ft": 12, "airport_type": "large_airport", "pax_annual": 52.7, "runways": 3, "continent": "EU"},
    {"iata": "FCO", "icao": "LIRF", "name": "Rome Fiumicino", "city": "Rome", "country_iso": "ITA", "lat": 41.8003, "lon": 12.2389, "elevation_ft": 15, "airport_type": "large_airport", "pax_annual": 49.4, "runways": 4, "continent": "EU"},
    {"iata": "MUC", "icao": "EDDM", "name": "Munich Airport", "city": "Munich", "country_iso": "DEU", "lat": 48.3537, "lon": 11.7750, "elevation_ft": 1487, "airport_type": "large_airport", "pax_annual": 47.9, "runways": 2, "continent": "EU"},
    {"iata": "LGW", "icao": "EGKK", "name": "London Gatwick", "city": "London", "country_iso": "GBR", "lat": 51.1537, "lon": -0.1821, "elevation_ft": 202, "airport_type": "large_airport", "pax_annual": 40.9, "runways": 2, "continent": "EU"},
    {"iata": "ZRH", "icao": "LSZH", "name": "Zürich Airport", "city": "Zürich", "country_iso": "CHE", "lat": 47.4647, "lon": 8.5492, "elevation_ft": 1416, "airport_type": "large_airport", "pax_annual": 31.5, "runways": 3, "continent": "EU"},
    {"iata": "CPH", "icao": "EKCH", "name": "Copenhagen Airport", "city": "Copenhagen", "country_iso": "DNK", "lat": 55.6181, "lon": 12.6561, "elevation_ft": 17, "airport_type": "large_airport", "pax_annual": 30.3, "runways": 3, "continent": "EU"},
    {"iata": "DUB", "icao": "EIDW", "name": "Dublin Airport", "city": "Dublin", "country_iso": "IRL", "lat": 53.4264, "lon": -6.2499, "elevation_ft": 242, "airport_type": "large_airport", "pax_annual": 32.9, "runways": 2, "continent": "EU"},
    {"iata": "VIE", "icao": "LOWW", "name": "Vienna Intl Airport", "city": "Vienna", "country_iso": "AUT", "lat": 48.1103, "lon": 16.5697, "elevation_ft": 600, "airport_type": "large_airport", "pax_annual": 31.7, "runways": 2, "continent": "EU"},
    {"iata": "OSL", "icao": "ENGM", "name": "Oslo Gardermoen", "city": "Oslo", "country_iso": "NOR", "lat": 60.1976, "lon": 11.1004, "elevation_ft": 681, "airport_type": "large_airport", "pax_annual": 28.6, "runways": 2, "continent": "EU"},
    {"iata": "ARN", "icao": "ESSA", "name": "Stockholm Arlanda", "city": "Stockholm", "country_iso": "SWE", "lat": 59.6498, "lon": 17.9238, "elevation_ft": 137, "airport_type": "large_airport", "pax_annual": 26.8, "runways": 3, "continent": "EU"},
    {"iata": "BRU", "icao": "EBBR", "name": "Brussels Airport", "city": "Brussels", "country_iso": "BEL", "lat": 50.9014, "lon": 4.4844, "elevation_ft": 184, "airport_type": "large_airport", "pax_annual": 25.7, "runways": 3, "continent": "EU"},
    {"iata": "HEL", "icao": "EFHK", "name": "Helsinki-Vantaa", "city": "Helsinki", "country_iso": "FIN", "lat": 60.3172, "lon": 24.9633, "elevation_ft": 179, "airport_type": "large_airport", "pax_annual": 22.0, "runways": 3, "continent": "EU"},
    {"iata": "WAW", "icao": "EPWA", "name": "Warsaw Chopin", "city": "Warsaw", "country_iso": "POL", "lat": 52.1657, "lon": 20.9671, "elevation_ft": 362, "airport_type": "large_airport", "pax_annual": 18.9, "runways": 2, "continent": "EU"},
    {"iata": "LIS", "icao": "LPPT", "name": "Lisbon Humberto Delgado", "city": "Lisbon", "country_iso": "PRT", "lat": 38.7742, "lon": -9.1342, "elevation_ft": 374, "airport_type": "large_airport", "pax_annual": 31.2, "runways": 2, "continent": "EU"},
    {"iata": "ATH", "icao": "LGAV", "name": "Athens Eleftherios Venizelos", "city": "Athens", "country_iso": "GRC", "lat": 37.9364, "lon": 23.9445, "elevation_ft": 308, "airport_type": "large_airport", "pax_annual": 28.2, "runways": 2, "continent": "EU"},
    {"iata": "SVO", "icao": "UUEE", "name": "Moscow Sheremetyevo", "city": "Moscow", "country_iso": "RUS", "lat": 55.9726, "lon": 37.4146, "elevation_ft": 630, "airport_type": "large_airport", "pax_annual": 49.9, "runways": 3, "continent": "EU"},
    # ── Europe (additional) ──
    {"iata": "SAW", "icao": "LTFJ", "name": "Istanbul Sabiha Gökçen", "city": "Istanbul", "country_iso": "TUR", "lat": 40.8986, "lon": 29.3092, "elevation_ft": 312, "airport_type": "large_airport", "pax_annual": 35.6, "runways": 2, "continent": "EU"},
    {"iata": "AYT", "icao": "LTAI", "name": "Antalya", "city": "Antalya", "country_iso": "TUR", "lat": 36.8987, "lon": 30.8005, "elevation_ft": 177, "airport_type": "large_airport", "pax_annual": 35.5, "runways": 2, "continent": "EU"},
    {"iata": "ORY", "icao": "LFPO", "name": "Paris Orly", "city": "Paris", "country_iso": "FRA", "lat": 48.7233, "lon": 2.3794, "elevation_ft": 292, "airport_type": "large_airport", "pax_annual": 33.1, "runways": 3, "continent": "EU"},
    {"iata": "PMI", "icao": "LEPA", "name": "Palma de Mallorca", "city": "Palma", "country_iso": "ESP", "lat": 39.5517, "lon": 2.7388, "elevation_ft": 27, "airport_type": "large_airport", "pax_annual": 31.1, "runways": 2, "continent": "EU"},
    {"iata": "MXP", "icao": "LIMC", "name": "Milan Malpensa", "city": "Milan", "country_iso": "ITA", "lat": 45.6306, "lon": 8.7281, "elevation_ft": 768, "airport_type": "large_airport", "pax_annual": 28.8, "runways": 2, "continent": "EU"},
    {"iata": "MAN", "icao": "EGCC", "name": "Manchester", "city": "Manchester", "country_iso": "GBR", "lat": 53.3537, "lon": -2.2750, "elevation_ft": 257, "airport_type": "large_airport", "pax_annual": 28.3, "runways": 2, "continent": "EU"},
    {"iata": "STN", "icao": "EGSS", "name": "London Stansted", "city": "London", "country_iso": "GBR", "lat": 51.8850, "lon": 0.2350, "elevation_ft": 348, "airport_type": "large_airport", "pax_annual": 28.0, "runways": 1, "continent": "EU"},
    {"iata": "BER", "icao": "EDDB", "name": "Berlin Brandenburg", "city": "Berlin", "country_iso": "DEU", "lat": 52.3667, "lon": 13.5033, "elevation_ft": 157, "airport_type": "large_airport", "pax_annual": 25.5, "runways": 2, "continent": "EU"},
    {"iata": "DUS", "icao": "EDDL", "name": "Düsseldorf", "city": "Düsseldorf", "country_iso": "DEU", "lat": 51.2895, "lon": 6.7668, "elevation_ft": 147, "airport_type": "large_airport", "pax_annual": 25.5, "runways": 2, "continent": "EU"},
    {"iata": "AGP", "icao": "LEMG", "name": "Malaga-Costa del Sol", "city": "Malaga", "country_iso": "ESP", "lat": 36.6749, "lon": -4.4991, "elevation_ft": 53, "airport_type": "large_airport", "pax_annual": 22.0, "runways": 2, "continent": "EU"},
    {"iata": "GVA", "icao": "LSGG", "name": "Geneva", "city": "Geneva", "country_iso": "CHE", "lat": 46.2381, "lon": 6.1089, "elevation_ft": 1411, "airport_type": "large_airport", "pax_annual": 17.9, "runways": 1, "continent": "EU"},
    {"iata": "PRG", "icao": "LKPR", "name": "Prague Vaclav Havel", "city": "Prague", "country_iso": "CZE", "lat": 50.1008, "lon": 14.2600, "elevation_ft": 1247, "airport_type": "large_airport", "pax_annual": 17.8, "runways": 2, "continent": "EU"},
    {"iata": "HAM", "icao": "EDDH", "name": "Hamburg", "city": "Hamburg", "country_iso": "DEU", "lat": 53.6304, "lon": 9.9882, "elevation_ft": 53, "airport_type": "large_airport", "pax_annual": 17.3, "runways": 2, "continent": "EU"},
    {"iata": "BUD", "icao": "LHBP", "name": "Budapest Ferenc Liszt", "city": "Budapest", "country_iso": "HUN", "lat": 47.4369, "lon": 19.2556, "elevation_ft": 495, "airport_type": "large_airport", "pax_annual": 16.2, "runways": 2, "continent": "EU"},
    {"iata": "BGY", "icao": "LIME", "name": "Milan Bergamo", "city": "Bergamo", "country_iso": "ITA", "lat": 45.6739, "lon": 9.7042, "elevation_ft": 782, "airport_type": "large_airport", "pax_annual": 15.4, "runways": 1, "continent": "EU"},
    {"iata": "OTP", "icao": "LROP", "name": "Bucharest Henri Coanda", "city": "Bucharest", "country_iso": "ROU", "lat": 44.5711, "lon": 26.0850, "elevation_ft": 314, "airport_type": "large_airport", "pax_annual": 14.7, "runways": 1, "continent": "EU"},
    {"iata": "EDI", "icao": "EGPH", "name": "Edinburgh", "city": "Edinburgh", "country_iso": "GBR", "lat": 55.9500, "lon": -3.3725, "elevation_ft": 135, "airport_type": "large_airport", "pax_annual": 14.7, "runways": 1, "continent": "EU"},
    {"iata": "NCE", "icao": "LFMN", "name": "Nice Côte d Azur", "city": "Nice", "country_iso": "FRA", "lat": 43.6584, "lon": 7.2159, "elevation_ft": 12, "airport_type": "large_airport", "pax_annual": 14.5, "runways": 2, "continent": "EU"},
    {"iata": "NAP", "icao": "LIRN", "name": "Naples", "city": "Naples", "country_iso": "ITA", "lat": 40.8860, "lon": 14.2908, "elevation_ft": 294, "airport_type": "large_airport", "pax_annual": 12.5, "runways": 1, "continent": "EU"},
    {"iata": "LYS", "icao": "LFLL", "name": "Lyon-Saint Exupéry", "city": "Lyon", "country_iso": "FRA", "lat": 45.7256, "lon": 5.0811, "elevation_ft": 821, "airport_type": "large_airport", "pax_annual": 12.1, "runways": 2, "continent": "EU"},
    {"iata": "RIX", "icao": "EVRA", "name": "Riga Intl", "city": "Riga", "country_iso": "LVA", "lat": 56.9236, "lon": 23.9711, "elevation_ft": 36, "airport_type": "large_airport", "pax_annual": 7.8, "runways": 1, "continent": "EU"},
    {"iata": "BEG", "icao": "LYBE", "name": "Belgrade Nikola Tesla", "city": "Belgrade", "country_iso": "SRB", "lat": 44.8184, "lon": 20.3091, "elevation_ft": 335, "airport_type": "large_airport", "pax_annual": 7.5, "runways": 1, "continent": "EU"},
    {"iata": "KEF", "icao": "BIKF", "name": "Keflavik Intl", "city": "Reykjavik", "country_iso": "ISL", "lat": 63.9850, "lon": -22.6056, "elevation_ft": 171, "airport_type": "large_airport", "pax_annual": 7.2, "runways": 2, "continent": "EU"},
    {"iata": "SOF", "icao": "LBSF", "name": "Sofia", "city": "Sofia", "country_iso": "BGR", "lat": 42.6952, "lon": 23.4064, "elevation_ft": 1742, "airport_type": "large_airport", "pax_annual": 7.1, "runways": 1, "continent": "EU"},
    {"iata": "ZAG", "icao": "LDZA", "name": "Zagreb Franjo Tudman", "city": "Zagreb", "country_iso": "HRV", "lat": 45.7429, "lon": 16.0688, "elevation_ft": 353, "airport_type": "large_airport", "pax_annual": 3.8, "runways": 1, "continent": "EU"},

    # ── Middle East ──
    {"iata": "DXB", "icao": "OMDB", "name": "Dubai Intl", "city": "Dubai", "country_iso": "ARE", "lat": 25.2528, "lon": 55.3644, "elevation_ft": 62, "airport_type": "large_airport", "pax_annual": 87.0, "runways": 2, "continent": "AS"},
    {"iata": "DOH", "icao": "OTHH", "name": "Hamad Intl", "city": "Doha", "country_iso": "QAT", "lat": 25.2731, "lon": 51.6081, "elevation_ft": 13, "airport_type": "large_airport", "pax_annual": 46.1, "runways": 2, "continent": "AS"},
    {"iata": "AUH", "icao": "OMAA", "name": "Abu Dhabi Intl", "city": "Abu Dhabi", "country_iso": "ARE", "lat": 24.4331, "lon": 54.6511, "elevation_ft": 88, "airport_type": "large_airport", "pax_annual": 24.5, "runways": 2, "continent": "AS"},
    {"iata": "JED", "icao": "OEJN", "name": "King Abdulaziz Intl", "city": "Jeddah", "country_iso": "SAU", "lat": 21.6796, "lon": 39.1565, "elevation_ft": 48, "airport_type": "large_airport", "pax_annual": 46.4, "runways": 2, "continent": "AS"},
    {"iata": "RUH", "icao": "OERK", "name": "King Khalid Intl", "city": "Riyadh", "country_iso": "SAU", "lat": 24.9576, "lon": 46.6988, "elevation_ft": 2049, "airport_type": "large_airport", "pax_annual": 29.5, "runways": 2, "continent": "AS"},
    {"iata": "TLV", "icao": "LLBG", "name": "Ben Gurion Intl", "city": "Tel Aviv", "country_iso": "ISR", "lat": 32.0114, "lon": 34.8867, "elevation_ft": 135, "airport_type": "large_airport", "pax_annual": 25.0, "runways": 3, "continent": "AS"},

    # ── Asia-Pacific ──
    {"iata": "PEK", "icao": "ZBAA", "name": "Beijing Capital Intl", "city": "Beijing", "country_iso": "CHN", "lat": 40.0799, "lon": 116.6031, "elevation_ft": 116, "airport_type": "large_airport", "pax_annual": 100.0, "runways": 3, "continent": "AS"},
    {"iata": "PKX", "icao": "ZBAD", "name": "Beijing Daxing Intl", "city": "Beijing", "country_iso": "CHN", "lat": 39.5098, "lon": 116.4105, "elevation_ft": 98, "airport_type": "large_airport", "pax_annual": 39.1, "runways": 4, "continent": "AS"},
    {"iata": "HND", "icao": "RJTT", "name": "Tokyo Haneda", "city": "Tokyo", "country_iso": "JPN", "lat": 35.5494, "lon": 139.7798, "elevation_ft": 35, "airport_type": "large_airport", "pax_annual": 87.1, "runways": 4, "continent": "AS"},
    {"iata": "PVG", "icao": "ZSPD", "name": "Shanghai Pudong Intl", "city": "Shanghai", "country_iso": "CHN", "lat": 31.1443, "lon": 121.8083, "elevation_ft": 13, "airport_type": "large_airport", "pax_annual": 76.2, "runways": 5, "continent": "AS"},
    {"iata": "CAN", "icao": "ZGGG", "name": "Guangzhou Baiyun Intl", "city": "Guangzhou", "country_iso": "CHN", "lat": 23.3924, "lon": 113.2988, "elevation_ft": 49, "airport_type": "large_airport", "pax_annual": 73.4, "runways": 3, "continent": "AS"},
    {"iata": "SIN", "icao": "WSSS", "name": "Singapore Changi", "city": "Singapore", "country_iso": "SGP", "lat": 1.3644, "lon": 103.9915, "elevation_ft": 22, "airport_type": "large_airport", "pax_annual": 68.3, "runways": 2, "continent": "AS"},
    {"iata": "ICN", "icao": "RKSI", "name": "Seoul Incheon Intl", "city": "Seoul", "country_iso": "KOR", "lat": 37.4602, "lon": 126.4407, "elevation_ft": 23, "airport_type": "large_airport", "pax_annual": 71.2, "runways": 4, "continent": "AS"},
    {"iata": "BKK", "icao": "VTBS", "name": "Bangkok Suvarnabhumi", "city": "Bangkok", "country_iso": "THA", "lat": 13.6900, "lon": 100.7501, "elevation_ft": 5, "airport_type": "large_airport", "pax_annual": 65.4, "runways": 2, "continent": "AS"},
    {"iata": "DEL", "icao": "VIDP", "name": "Indira Gandhi Intl", "city": "Delhi", "country_iso": "IND", "lat": 28.5562, "lon": 77.1000, "elevation_ft": 777, "airport_type": "large_airport", "pax_annual": 72.3, "runways": 3, "continent": "AS"},
    {"iata": "BOM", "icao": "VABB", "name": "Chhatrapati Shivaji Maharaj Intl", "city": "Mumbai", "country_iso": "IND", "lat": 19.0896, "lon": 72.8656, "elevation_ft": 39, "airport_type": "large_airport", "pax_annual": 51.8, "runways": 2, "continent": "AS"},
    {"iata": "HKG", "icao": "VHHH", "name": "Hong Kong Intl", "city": "Hong Kong", "country_iso": "CHN", "lat": 22.3080, "lon": 113.9185, "elevation_ft": 28, "airport_type": "large_airport", "pax_annual": 50.9, "runways": 2, "continent": "AS"},
    {"iata": "KUL", "icao": "WMKK", "name": "Kuala Lumpur Intl", "city": "Kuala Lumpur", "country_iso": "MYS", "lat": 2.7456, "lon": 101.7099, "elevation_ft": 69, "airport_type": "large_airport", "pax_annual": 62.3, "runways": 2, "continent": "AS"},
    {"iata": "NRT", "icao": "RJAA", "name": "Tokyo Narita Intl", "city": "Tokyo", "country_iso": "JPN", "lat": 35.7647, "lon": 140.3864, "elevation_ft": 141, "airport_type": "large_airport", "pax_annual": 35.5, "runways": 2, "continent": "AS"},
    {"iata": "CGK", "icao": "WIII", "name": "Jakarta Soekarno-Hatta Intl", "city": "Jakarta", "country_iso": "IDN", "lat": -6.1256, "lon": 106.6558, "elevation_ft": 34, "airport_type": "large_airport", "pax_annual": 65.0, "runways": 2, "continent": "AS"},
    {"iata": "MNL", "icao": "RPLL", "name": "Manila Ninoy Aquino Intl", "city": "Manila", "country_iso": "PHL", "lat": 14.5086, "lon": 121.0197, "elevation_ft": 75, "airport_type": "large_airport", "pax_annual": 47.9, "runways": 2, "continent": "AS"},
    {"iata": "SYD", "icao": "YSSY", "name": "Sydney Kingsford Smith", "city": "Sydney", "country_iso": "AUS", "lat": -33.9461, "lon": 151.1772, "elevation_ft": 21, "airport_type": "large_airport", "pax_annual": 44.4, "runways": 3, "continent": "OC"},
    {"iata": "MEL", "icao": "YMML", "name": "Melbourne Tullamarine", "city": "Melbourne", "country_iso": "AUS", "lat": -37.6690, "lon": 144.8410, "elevation_ft": 434, "airport_type": "large_airport", "pax_annual": 37.7, "runways": 2, "continent": "OC"},
    {"iata": "AKL", "icao": "NZAA", "name": "Auckland Intl", "city": "Auckland", "country_iso": "NZL", "lat": -37.0082, "lon": 174.7850, "elevation_ft": 23, "airport_type": "large_airport", "pax_annual": 21.4, "runways": 2, "continent": "OC"},
    {"iata": "TPE", "icao": "RCTP", "name": "Taiwan Taoyuan Intl", "city": "Taipei", "country_iso": "TWN", "lat": 25.0797, "lon": 121.2342, "elevation_ft": 106, "airport_type": "large_airport", "pax_annual": 48.7, "runways": 2, "continent": "AS"},
    {"iata": "BLR", "icao": "VOBL", "name": "Bengaluru Kempegowda Intl", "city": "Bengaluru", "country_iso": "IND", "lat": 13.1986, "lon": 77.7066, "elevation_ft": 3000, "airport_type": "large_airport", "pax_annual": 37.5, "runways": 2, "continent": "AS"},
    {"iata": "CTU", "icao": "ZUUU", "name": "Chengdu Tianfu Intl", "city": "Chengdu", "country_iso": "CHN", "lat": 30.3145, "lon": 104.4432, "elevation_ft": 1624, "airport_type": "large_airport", "pax_annual": 60.2, "runways": 3, "continent": "AS"},
    {"iata": "SZX", "icao": "ZGSZ", "name": "Shenzhen Bao'an Intl", "city": "Shenzhen", "country_iso": "CHN", "lat": 22.6393, "lon": 113.8107, "elevation_ft": 13, "airport_type": "large_airport", "pax_annual": 52.9, "runways": 2, "continent": "AS"},
    # ── Asia-Pacific (additional) ──
    {"iata": "KMG", "icao": "ZPPP", "name": "Kunming Changshui Intl", "city": "Kunming", "country_iso": "CHN", "lat": 25.1022, "lon": 102.9291, "elevation_ft": 6903, "airport_type": "large_airport", "pax_annual": 48.1, "runways": 2, "continent": "AS"},
    {"iata": "SHA", "icao": "ZSSS", "name": "Shanghai Hongqiao Intl", "city": "Shanghai", "country_iso": "CHN", "lat": 31.1979, "lon": 121.3362, "elevation_ft": 10, "airport_type": "large_airport", "pax_annual": 45.6, "runways": 2, "continent": "AS"},
    {"iata": "XIY", "icao": "ZLXY", "name": "Xi an Xianyang Intl", "city": "Xi an", "country_iso": "CHN", "lat": 34.4471, "lon": 108.7516, "elevation_ft": 1572, "airport_type": "large_airport", "pax_annual": 44.7, "runways": 2, "continent": "AS"},
    {"iata": "CKG", "icao": "ZUCK", "name": "Chongqing Jiangbei Intl", "city": "Chongqing", "country_iso": "CHN", "lat": 29.7192, "lon": 106.6422, "elevation_ft": 1365, "airport_type": "large_airport", "pax_annual": 44.4, "runways": 3, "continent": "AS"},
    {"iata": "SGN", "icao": "VVTS", "name": "Tan Son Nhat Intl", "city": "Ho Chi Minh City", "country_iso": "VNM", "lat": 10.8188, "lon": 106.6520, "elevation_ft": 33, "airport_type": "large_airport", "pax_annual": 41.2, "runways": 2, "continent": "AS"},
    {"iata": "DMK", "icao": "VTBD", "name": "Bangkok Don Mueang", "city": "Bangkok", "country_iso": "THA", "lat": 13.9126, "lon": 100.6070, "elevation_ft": 9, "airport_type": "large_airport", "pax_annual": 40.5, "runways": 2, "continent": "AS"},
    {"iata": "HGH", "icao": "ZSHC", "name": "Hangzhou Xiaoshan Intl", "city": "Hangzhou", "country_iso": "CHN", "lat": 30.2295, "lon": 120.4344, "elevation_ft": 23, "airport_type": "large_airport", "pax_annual": 40.1, "runways": 2, "continent": "AS"},
    {"iata": "KIX", "icao": "RJBB", "name": "Osaka Kansai Intl", "city": "Osaka", "country_iso": "JPN", "lat": 34.4347, "lon": 135.2440, "elevation_ft": 26, "airport_type": "large_airport", "pax_annual": 31.9, "runways": 2, "continent": "AS"},
    {"iata": "HAN", "icao": "VVNB", "name": "Noi Bai Intl", "city": "Hanoi", "country_iso": "VNM", "lat": 21.2212, "lon": 105.8072, "elevation_ft": 39, "airport_type": "large_airport", "pax_annual": 29.4, "runways": 2, "continent": "AS"},
    {"iata": "GMP", "icao": "RKSS", "name": "Seoul Gimpo Intl", "city": "Seoul", "country_iso": "KOR", "lat": 37.5583, "lon": 126.7906, "elevation_ft": 59, "airport_type": "large_airport", "pax_annual": 26.3, "runways": 2, "continent": "AS"},
    {"iata": "HYD", "icao": "VOHS", "name": "Rajiv Gandhi Intl", "city": "Hyderabad", "country_iso": "IND", "lat": 17.2403, "lon": 78.4294, "elevation_ft": 2024, "airport_type": "large_airport", "pax_annual": 25.2, "runways": 1, "continent": "AS"},
    {"iata": "FUK", "icao": "RJFF", "name": "Fukuoka", "city": "Fukuoka", "country_iso": "JPN", "lat": 33.5859, "lon": 130.4511, "elevation_ft": 30, "airport_type": "large_airport", "pax_annual": 24.8, "runways": 1, "continent": "AS"},
    {"iata": "CTS", "icao": "RJCC", "name": "New Chitose (Sapporo)", "city": "Sapporo", "country_iso": "JPN", "lat": 42.7752, "lon": 141.6924, "elevation_ft": 82, "airport_type": "large_airport", "pax_annual": 23.6, "runways": 2, "continent": "AS"},
    {"iata": "MAA", "icao": "VOMM", "name": "Chennai Intl", "city": "Chennai", "country_iso": "IND", "lat": 12.9941, "lon": 80.1709, "elevation_ft": 52, "airport_type": "large_airport", "pax_annual": 23.4, "runways": 2, "continent": "AS"},
    {"iata": "CCU", "icao": "VECC", "name": "Netaji Subhas Chandra Bose Intl", "city": "Kolkata", "country_iso": "IND", "lat": 22.6547, "lon": 88.4467, "elevation_ft": 16, "airport_type": "large_airport", "pax_annual": 20.8, "runways": 2, "continent": "AS"},
    {"iata": "PUS", "icao": "RKPK", "name": "Busan Gimhae Intl", "city": "Busan", "country_iso": "KOR", "lat": 35.1795, "lon": 128.9382, "elevation_ft": 6, "airport_type": "large_airport", "pax_annual": 17.6, "runways": 2, "continent": "AS"},
    {"iata": "MCT", "icao": "OOMS", "name": "Muscat Intl", "city": "Muscat", "country_iso": "OMN", "lat": 23.5933, "lon": 58.2844, "elevation_ft": 48, "airport_type": "large_airport", "pax_annual": 16.0, "runways": 1, "continent": "AS"},
    {"iata": "KWI", "icao": "OKBK", "name": "Kuwait Intl", "city": "Kuwait City", "country_iso": "KWT", "lat": 29.2266, "lon": 47.9689, "elevation_ft": 206, "airport_type": "large_airport", "pax_annual": 15.6, "runways": 2, "continent": "AS"},
    {"iata": "CEB", "icao": "RPVM", "name": "Mactan-Cebu Intl", "city": "Cebu", "country_iso": "PHL", "lat": 10.3074, "lon": 123.9794, "elevation_ft": 31, "airport_type": "large_airport", "pax_annual": 12.8, "runways": 1, "continent": "AS"},
    {"iata": "DAC", "icao": "VGHS", "name": "Hazrat Shahjalal Intl", "city": "Dhaka", "country_iso": "BGD", "lat": 23.8433, "lon": 90.3978, "elevation_ft": 30, "airport_type": "large_airport", "pax_annual": 12.0, "runways": 1, "continent": "AS"},
    {"iata": "CMB", "icao": "VCBI", "name": "Bandaranaike Intl", "city": "Colombo", "country_iso": "LKA", "lat": 7.1808, "lon": 79.8841, "elevation_ft": 30, "airport_type": "large_airport", "pax_annual": 10.3, "runways": 1, "continent": "AS"},
    {"iata": "BAH", "icao": "OBBI", "name": "Bahrain Intl", "city": "Muharraq", "country_iso": "BHR", "lat": 26.2708, "lon": 50.6336, "elevation_ft": 6, "airport_type": "large_airport", "pax_annual": 9.6, "runways": 1, "continent": "AS"},
    {"iata": "ISB", "icao": "OPIS", "name": "Islamabad Intl", "city": "Islamabad", "country_iso": "PAK", "lat": 33.5605, "lon": 72.8526, "elevation_ft": 1761, "airport_type": "large_airport", "pax_annual": 9.2, "runways": 2, "continent": "AS"},
    {"iata": "AMM", "icao": "OJAI", "name": "Queen Alia Intl", "city": "Amman", "country_iso": "JOR", "lat": 31.7226, "lon": 35.9932, "elevation_ft": 2395, "airport_type": "large_airport", "pax_annual": 8.9, "runways": 2, "continent": "AS"},
    # ── Oceania (additional) ──
    {"iata": "BNE", "icao": "YBBN", "name": "Brisbane", "city": "Brisbane", "country_iso": "AUS", "lat": -27.3842, "lon": 153.1175, "elevation_ft": 13, "airport_type": "large_airport", "pax_annual": 23.7, "runways": 2, "continent": "OC"},
    {"iata": "PER", "icao": "YPPH", "name": "Perth", "city": "Perth", "country_iso": "AUS", "lat": -31.9403, "lon": 115.9672, "elevation_ft": 67, "airport_type": "large_airport", "pax_annual": 14.1, "runways": 2, "continent": "OC"},

    # ── South America ──
    {"iata": "GRU", "icao": "SBGR", "name": "São Paulo Guarulhos Intl", "city": "São Paulo", "country_iso": "BRA", "lat": -23.4356, "lon": -46.4731, "elevation_ft": 2459, "airport_type": "large_airport", "pax_annual": 41.3, "runways": 2, "continent": "SA"},
    {"iata": "BOG", "icao": "SKBO", "name": "Bogotá El Dorado Intl", "city": "Bogotá", "country_iso": "COL", "lat": 4.7016, "lon": -74.1469, "elevation_ft": 8361, "airport_type": "large_airport", "pax_annual": 38.1, "runways": 2, "continent": "SA"},
    {"iata": "SCL", "icao": "SCEL", "name": "Santiago Arturo Merino Benítez Intl", "city": "Santiago", "country_iso": "CHL", "lat": -33.3930, "lon": -70.7858, "elevation_ft": 1555, "airport_type": "large_airport", "pax_annual": 24.0, "runways": 2, "continent": "SA"},
    {"iata": "EZE", "icao": "SAEZ", "name": "Buenos Aires Ministro Pistarini Intl", "city": "Buenos Aires", "country_iso": "ARG", "lat": -34.8222, "lon": -58.5358, "elevation_ft": 67, "airport_type": "large_airport", "pax_annual": 14.2, "runways": 2, "continent": "SA"},
    {"iata": "LIM", "icao": "SPJC", "name": "Lima Jorge Chávez Intl", "city": "Lima", "country_iso": "PER", "lat": -12.0219, "lon": -77.1143, "elevation_ft": 113, "airport_type": "large_airport", "pax_annual": 24.8, "runways": 2, "continent": "SA"},
    {"iata": "GIG", "icao": "SBGL", "name": "Rio de Janeiro Galeão Intl", "city": "Rio de Janeiro", "country_iso": "BRA", "lat": -22.8100, "lon": -43.2506, "elevation_ft": 28, "airport_type": "large_airport", "pax_annual": 16.1, "runways": 2, "continent": "SA"},
    {"iata": "PTY", "icao": "MPTO", "name": "Panama City Tocumen Intl", "city": "Panama City", "country_iso": "PAN", "lat": 9.0714, "lon": -79.3835, "elevation_ft": 135, "airport_type": "large_airport", "pax_annual": 16.7, "runways": 2, "continent": "NA"},

    # ── Africa ──
    {"iata": "JNB", "icao": "FAOR", "name": "Johannesburg O.R. Tambo Intl", "city": "Johannesburg", "country_iso": "ZAF", "lat": -26.1392, "lon": 28.2460, "elevation_ft": 5558, "airport_type": "large_airport", "pax_annual": 21.7, "runways": 2, "continent": "AF"},
    {"iata": "CAI", "icao": "HECA", "name": "Cairo Intl", "city": "Cairo", "country_iso": "EGY", "lat": 30.1219, "lon": 31.4056, "elevation_ft": 382, "airport_type": "large_airport", "pax_annual": 22.1, "runways": 3, "continent": "AF"},
    {"iata": "ADD", "icao": "HAAB", "name": "Addis Ababa Bole Intl", "city": "Addis Ababa", "country_iso": "ETH", "lat": 8.9779, "lon": 38.7993, "elevation_ft": 7625, "airport_type": "large_airport", "pax_annual": 15.3, "runways": 2, "continent": "AF"},
    {"iata": "CMN", "icao": "GMMN", "name": "Casablanca Mohammed V Intl", "city": "Casablanca", "country_iso": "MAR", "lat": 33.3675, "lon": -7.5898, "elevation_ft": 656, "airport_type": "large_airport", "pax_annual": 10.3, "runways": 2, "continent": "AF"},
    {"iata": "NBO", "icao": "HKJK", "name": "Nairobi Jomo Kenyatta Intl", "city": "Nairobi", "country_iso": "KEN", "lat": -1.3192, "lon": 36.9278, "elevation_ft": 5327, "airport_type": "large_airport", "pax_annual": 8.1, "runways": 1, "continent": "AF"},
    {"iata": "LOS", "icao": "DNMM", "name": "Lagos Murtala Muhammed Intl", "city": "Lagos", "country_iso": "NGA", "lat": 6.5774, "lon": 3.3215, "elevation_ft": 135, "airport_type": "large_airport", "pax_annual": 9.2, "runways": 2, "continent": "AF"},
    {"iata": "CPT", "icao": "FACT", "name": "Cape Town Intl", "city": "Cape Town", "country_iso": "ZAF", "lat": -33.9715, "lon": 18.6021, "elevation_ft": 151, "airport_type": "large_airport", "pax_annual": 10.8, "runways": 1, "continent": "AF"},
    {"iata": "ALG", "icao": "DAAG", "name": "Algiers Houari Boumediene", "city": "Algiers", "country_iso": "DZA", "lat": 36.6910, "lon": 3.2154, "elevation_ft": 82, "airport_type": "large_airport", "pax_annual": 10.0, "runways": 2, "continent": "AF"},
    {"iata": "DAR", "icao": "HTDA", "name": "Dar es Salaam Julius Nyerere Intl", "city": "Dar es Salaam", "country_iso": "TZA", "lat": -6.8781, "lon": 39.2026, "elevation_ft": 186, "airport_type": "medium_airport", "pax_annual": 4.2, "runways": 1, "continent": "AF"},
    {"iata": "ACC", "icao": "DGAA", "name": "Accra Kotoka Intl", "city": "Accra", "country_iso": "GHA", "lat": 5.6052, "lon": -0.1668, "elevation_ft": 205, "airport_type": "large_airport", "pax_annual": 3.4, "runways": 1, "continent": "AF"},

    # ── Central Asia & Russia ──
    {"iata": "LED", "icao": "ULLI", "name": "St Petersburg Pulkovo", "city": "St Petersburg", "country_iso": "RUS", "lat": 59.8003, "lon": 30.2625, "elevation_ft": 78, "airport_type": "large_airport", "pax_annual": 19.6, "runways": 2, "continent": "EU"},
    {"iata": "DME", "icao": "UUDD", "name": "Moscow Domodedovo", "city": "Moscow", "country_iso": "RUS", "lat": 55.4088, "lon": 37.9063, "elevation_ft": 588, "airport_type": "large_airport", "pax_annual": 30.3, "runways": 2, "continent": "EU"},
    {"iata": "ALA", "icao": "UAAA", "name": "Almaty Intl", "city": "Almaty", "country_iso": "KAZ", "lat": 43.3521, "lon": 77.0405, "elevation_ft": 2234, "airport_type": "large_airport", "pax_annual": 7.5, "runways": 1, "continent": "AS"},
    {"iata": "TAS", "icao": "UTTT", "name": "Tashkent Intl", "city": "Tashkent", "country_iso": "UZB", "lat": 41.2579, "lon": 69.2812, "elevation_ft": 1417, "airport_type": "large_airport", "pax_annual": 5.0, "runways": 1, "continent": "AS"},

    # ── Africa (expansion) ──
    {"iata": "TUN", "icao": "DTTA", "name": "Tunis-Carthage Intl", "city": "Tunis", "country_iso": "TUN", "lat": 36.8510, "lon": 10.2272, "elevation_ft": 22, "airport_type": "large_airport", "pax_annual": 6.5, "runways": 1, "continent": "AF"},
    {"iata": "LAD", "icao": "FNLU", "name": "Quatro de Fevereiro Intl", "city": "Luanda", "country_iso": "AGO", "lat": -8.8584, "lon": 13.2312, "elevation_ft": 243, "airport_type": "large_airport", "pax_annual": 4.5, "runways": 1, "continent": "AF"},
    {"iata": "ABV", "icao": "DNAA", "name": "Nnamdi Azikiwe Intl", "city": "Abuja", "country_iso": "NGA", "lat": 9.0065, "lon": 7.2632, "elevation_ft": 1123, "airport_type": "large_airport", "pax_annual": 5.0, "runways": 1, "continent": "AF"},
    {"iata": "MRU", "icao": "FIMP", "name": "Sir Seewoosagur Ramgoolam Intl", "city": "Port Louis", "country_iso": "MUS", "lat": -20.4302, "lon": 57.6836, "elevation_ft": 186, "airport_type": "large_airport", "pax_annual": 4.0, "runways": 1, "continent": "AF"},
    {"iata": "DSS", "icao": "GOBD", "name": "Blaise Diagne Intl", "city": "Dakar", "country_iso": "SEN", "lat": 14.6700, "lon": -17.0733, "elevation_ft": 290, "airport_type": "large_airport", "pax_annual": 3.5, "runways": 1, "continent": "AF"},
    {"iata": "ABJ", "icao": "DIAP", "name": "Felix-Houphouet-Boigny Intl", "city": "Abidjan", "country_iso": "CIV", "lat": 5.2614, "lon": -3.9262, "elevation_ft": 21, "airport_type": "large_airport", "pax_annual": 2.5, "runways": 1, "continent": "AF"},
    {"iata": "EBB", "icao": "HUEN", "name": "Entebbe Intl", "city": "Entebbe", "country_iso": "UGA", "lat": 0.0424, "lon": 32.4435, "elevation_ft": 3782, "airport_type": "large_airport", "pax_annual": 1.9, "runways": 1, "continent": "AF"},
    {"iata": "KGL", "icao": "HRYR", "name": "Kigali Intl", "city": "Kigali", "country_iso": "RWA", "lat": -1.9686, "lon": 30.1395, "elevation_ft": 4859, "airport_type": "medium_airport", "pax_annual": 1.2, "runways": 1, "continent": "AF"},
    {"iata": "FIH", "icao": "FZAA", "name": "N Djili Intl", "city": "Kinshasa", "country_iso": "COD", "lat": -4.3858, "lon": 15.4446, "elevation_ft": 1027, "airport_type": "large_airport", "pax_annual": 1.5, "runways": 1, "continent": "AF"},
    {"iata": "LUN", "icao": "FLKK", "name": "Kenneth Kaunda Intl", "city": "Lusaka", "country_iso": "ZMB", "lat": -15.3309, "lon": 28.4526, "elevation_ft": 3779, "airport_type": "large_airport", "pax_annual": 1.5, "runways": 1, "continent": "AF"},
    {"iata": "HRE", "icao": "FVHA", "name": "Robert Gabriel Mugabe Intl", "city": "Harare", "country_iso": "ZWE", "lat": -17.9318, "lon": 31.0928, "elevation_ft": 4887, "airport_type": "large_airport", "pax_annual": 1.2, "runways": 1, "continent": "AF"},
    {"iata": "MPM", "icao": "FQMA", "name": "Maputo Intl", "city": "Maputo", "country_iso": "MOZ", "lat": -25.9208, "lon": 32.5726, "elevation_ft": 145, "airport_type": "medium_airport", "pax_annual": 1.5, "runways": 1, "continent": "AF"},
    {"iata": "DLA", "icao": "FKKD", "name": "Douala Intl", "city": "Douala", "country_iso": "CMR", "lat": 4.0061, "lon": 9.7194, "elevation_ft": 33, "airport_type": "medium_airport", "pax_annual": 1.5, "runways": 1, "continent": "AF"},
    {"iata": "WDH", "icao": "FYWH", "name": "Hosea Kutako Intl", "city": "Windhoek", "country_iso": "NAM", "lat": -22.4799, "lon": 17.4709, "elevation_ft": 5640, "airport_type": "medium_airport", "pax_annual": 0.8, "runways": 1, "continent": "AF"},
    {"iata": "TNR", "icao": "FMMI", "name": "Ivato Intl", "city": "Antananarivo", "country_iso": "MDG", "lat": -18.7969, "lon": 47.4789, "elevation_ft": 4198, "airport_type": "medium_airport", "pax_annual": 1.0, "runways": 1, "continent": "AF"},
    {"iata": "SEZ", "icao": "FSIA", "name": "Seychelles Intl", "city": "Mahe", "country_iso": "SYC", "lat": -4.6743, "lon": 55.5218, "elevation_ft": 10, "airport_type": "medium_airport", "pax_annual": 0.8, "runways": 1, "continent": "AF"},

    # ── South America (expansion) ──
    {"iata": "BSB", "icao": "SBBR", "name": "Brasilia Intl", "city": "Brasilia", "country_iso": "BRA", "lat": -15.8711, "lon": -47.9186, "elevation_ft": 3479, "airport_type": "large_airport", "pax_annual": 16.3, "runways": 2, "continent": "SA"},
    {"iata": "MDE", "icao": "SKRG", "name": "Jose Maria Cordova Intl", "city": "Medellin", "country_iso": "COL", "lat": 6.1645, "lon": -75.4231, "elevation_ft": 6955, "airport_type": "large_airport", "pax_annual": 9.0, "runways": 2, "continent": "SA"},
    {"iata": "CNF", "icao": "SBCF", "name": "Tancredo Neves Intl", "city": "Belo Horizonte", "country_iso": "BRA", "lat": -19.6244, "lon": -43.9719, "elevation_ft": 2715, "airport_type": "large_airport", "pax_annual": 10.5, "runways": 2, "continent": "SA"},
    {"iata": "POA", "icao": "SBPA", "name": "Salgado Filho Intl", "city": "Porto Alegre", "country_iso": "BRA", "lat": -29.9944, "lon": -51.1714, "elevation_ft": 11, "airport_type": "large_airport", "pax_annual": 8.5, "runways": 1, "continent": "SA"},
    {"iata": "SSA", "icao": "SBSV", "name": "Deputado Luis Eduardo Magalhaes Intl", "city": "Salvador", "country_iso": "BRA", "lat": -12.9086, "lon": -38.3225, "elevation_ft": 64, "airport_type": "large_airport", "pax_annual": 8.5, "runways": 2, "continent": "SA"},
    {"iata": "REC", "icao": "SBRF", "name": "Guararapes-Gilberto Freyre Intl", "city": "Recife", "country_iso": "BRA", "lat": -8.1264, "lon": -34.9236, "elevation_ft": 33, "airport_type": "large_airport", "pax_annual": 7.5, "runways": 1, "continent": "SA"},
    {"iata": "FOR", "icao": "SBFZ", "name": "Pinto Martins Intl", "city": "Fortaleza", "country_iso": "BRA", "lat": -3.7763, "lon": -38.5326, "elevation_ft": 82, "airport_type": "large_airport", "pax_annual": 7.0, "runways": 1, "continent": "SA"},
    {"iata": "CWB", "icao": "SBCT", "name": "Afonso Pena Intl", "city": "Curitiba", "country_iso": "BRA", "lat": -25.5285, "lon": -49.1758, "elevation_ft": 2988, "airport_type": "large_airport", "pax_annual": 6.5, "runways": 2, "continent": "SA"},
    {"iata": "CCS", "icao": "SVMI", "name": "Simon Bolivar Intl", "city": "Caracas", "country_iso": "VEN", "lat": 10.6012, "lon": -66.9913, "elevation_ft": 235, "airport_type": "large_airport", "pax_annual": 6.0, "runways": 2, "continent": "SA"},
    {"iata": "UIO", "icao": "SEQM", "name": "Mariscal Sucre Intl", "city": "Quito", "country_iso": "ECU", "lat": -0.1292, "lon": -78.3575, "elevation_ft": 7874, "airport_type": "large_airport", "pax_annual": 5.5, "runways": 1, "continent": "SA"},
    {"iata": "GYE", "icao": "SEGU", "name": "Jose Joaquin de Olmedo Intl", "city": "Guayaquil", "country_iso": "ECU", "lat": -2.1574, "lon": -79.8837, "elevation_ft": 19, "airport_type": "large_airport", "pax_annual": 4.5, "runways": 1, "continent": "SA"},
    {"iata": "VVI", "icao": "SLVR", "name": "Viru Viru Intl", "city": "Santa Cruz", "country_iso": "BOL", "lat": -17.6448, "lon": -63.1354, "elevation_ft": 1224, "airport_type": "large_airport", "pax_annual": 2.5, "runways": 1, "continent": "SA"},
    {"iata": "MVD", "icao": "SUMU", "name": "Carrasco Intl", "city": "Montevideo", "country_iso": "URY", "lat": -34.8384, "lon": -56.0308, "elevation_ft": 105, "airport_type": "large_airport", "pax_annual": 2.6, "runways": 1, "continent": "SA"},
    {"iata": "ASU", "icao": "SGAS", "name": "Silvio Pettirossi Intl", "city": "Asuncion", "country_iso": "PRY", "lat": -25.2400, "lon": -57.5191, "elevation_ft": 292, "airport_type": "large_airport", "pax_annual": 1.5, "runways": 1, "continent": "SA"},

    # ── Oceania (expansion) ──
    {"iata": "ADL", "icao": "YPAD", "name": "Adelaide", "city": "Adelaide", "country_iso": "AUS", "lat": -34.9450, "lon": 138.5306, "elevation_ft": 20, "airport_type": "large_airport", "pax_annual": 8.3, "runways": 2, "continent": "OC"},
    {"iata": "OOL", "icao": "YBCG", "name": "Gold Coast (Coolangatta)", "city": "Gold Coast", "country_iso": "AUS", "lat": -28.1644, "lon": 153.5047, "elevation_ft": 21, "airport_type": "large_airport", "pax_annual": 6.8, "runways": 1, "continent": "OC"},
    {"iata": "CHC", "icao": "NZCH", "name": "Christchurch Intl", "city": "Christchurch", "country_iso": "NZL", "lat": -43.4894, "lon": 172.5322, "elevation_ft": 123, "airport_type": "large_airport", "pax_annual": 6.8, "runways": 2, "continent": "OC"},
    {"iata": "WLG", "icao": "NZWN", "name": "Wellington Intl", "city": "Wellington", "country_iso": "NZL", "lat": -41.3272, "lon": 174.8053, "elevation_ft": 41, "airport_type": "large_airport", "pax_annual": 5.9, "runways": 1, "continent": "OC"},
    {"iata": "CNS", "icao": "YBCS", "name": "Cairns", "city": "Cairns", "country_iso": "AUS", "lat": -16.8858, "lon": 145.7554, "elevation_ft": 10, "airport_type": "large_airport", "pax_annual": 5.1, "runways": 1, "continent": "OC"},
    {"iata": "NAN", "icao": "NFFN", "name": "Nadi Intl", "city": "Nadi", "country_iso": "FJI", "lat": -17.7554, "lon": 177.4431, "elevation_ft": 59, "airport_type": "large_airport", "pax_annual": 2.3, "runways": 1, "continent": "OC"},
    {"iata": "POM", "icao": "AYPY", "name": "Jacksons Intl", "city": "Port Moresby", "country_iso": "PNG", "lat": -6.0228, "lon": 147.0070, "elevation_ft": 146, "airport_type": "large_airport", "pax_annual": 1.2, "runways": 1, "continent": "OC"},
    {"iata": "PPT", "icao": "NTAA", "name": "Tahiti Faa a Intl", "city": "Papeete", "country_iso": "PYF", "lat": -17.5537, "lon": -149.6073, "elevation_ft": 5, "airport_type": "medium_airport", "pax_annual": 1.5, "runways": 1, "continent": "OC"},

    # ── Asia (expansion) ──
    {"iata": "IKA", "icao": "OIIE", "name": "Imam Khomeini Intl", "city": "Tehran", "country_iso": "IRN", "lat": 35.4161, "lon": 51.1522, "elevation_ft": 3305, "airport_type": "large_airport", "pax_annual": 9.0, "runways": 2, "continent": "AS"},
    {"iata": "BGW", "icao": "ORBI", "name": "Baghdad Intl", "city": "Baghdad", "country_iso": "IRQ", "lat": 33.2625, "lon": 44.2346, "elevation_ft": 114, "airport_type": "large_airport", "pax_annual": 7.0, "runways": 2, "continent": "AS"},
    {"iata": "PNH", "icao": "VDPP", "name": "Phnom Penh Intl", "city": "Phnom Penh", "country_iso": "KHM", "lat": 11.5466, "lon": 104.8441, "elevation_ft": 40, "airport_type": "large_airport", "pax_annual": 6.5, "runways": 1, "continent": "AS"},
    {"iata": "RGN", "icao": "VYYY", "name": "Yangon Intl", "city": "Yangon", "country_iso": "MMR", "lat": 16.9073, "lon": 96.1332, "elevation_ft": 109, "airport_type": "large_airport", "pax_annual": 6.0, "runways": 1, "continent": "AS"},
    {"iata": "MLE", "icao": "VRMM", "name": "Velana Intl", "city": "Male", "country_iso": "MDV", "lat": 4.1918, "lon": 73.5290, "elevation_ft": 6, "airport_type": "large_airport", "pax_annual": 6.0, "runways": 1, "continent": "AS"},
    {"iata": "KTM", "icao": "VNKT", "name": "Tribhuvan Intl", "city": "Kathmandu", "country_iso": "NPL", "lat": 27.6966, "lon": 85.3591, "elevation_ft": 4390, "airport_type": "large_airport", "pax_annual": 6.0, "runways": 1, "continent": "AS"},
    {"iata": "GYD", "icao": "UBBB", "name": "Heydar Aliyev Intl", "city": "Baku", "country_iso": "AZE", "lat": 40.4675, "lon": 50.0467, "elevation_ft": -10, "airport_type": "large_airport", "pax_annual": 5.5, "runways": 2, "continent": "AS"},
    {"iata": "NQZ", "icao": "UACC", "name": "Nursultan Nazarbayev Intl", "city": "Astana", "country_iso": "KAZ", "lat": 51.0222, "lon": 71.4669, "elevation_ft": 1165, "airport_type": "large_airport", "pax_annual": 5.0, "runways": 1, "continent": "AS"},
    {"iata": "TBS", "icao": "UGTB", "name": "Shota Rustaveli Intl", "city": "Tbilisi", "country_iso": "GEO", "lat": 41.6692, "lon": 44.9547, "elevation_ft": 1624, "airport_type": "large_airport", "pax_annual": 4.0, "runways": 1, "continent": "AS"},
    {"iata": "FRU", "icao": "UCFM", "name": "Manas Intl", "city": "Bishkek", "country_iso": "KGZ", "lat": 43.0613, "lon": 74.4776, "elevation_ft": 2058, "airport_type": "large_airport", "pax_annual": 3.5, "runways": 1, "continent": "AS"},
    {"iata": "EVN", "icao": "UDYZ", "name": "Zvartnots Intl", "city": "Yerevan", "country_iso": "ARM", "lat": 40.1473, "lon": 44.3959, "elevation_ft": 2838, "airport_type": "large_airport", "pax_annual": 3.0, "runways": 1, "continent": "AS"},
    {"iata": "VTE", "icao": "VLVT", "name": "Wattay Intl", "city": "Vientiane", "country_iso": "LAO", "lat": 17.9883, "lon": 102.5633, "elevation_ft": 564, "airport_type": "medium_airport", "pax_annual": 1.5, "runways": 1, "continent": "AS"},
    {"iata": "ULN", "icao": "ZMUB", "name": "Chinggis Khaan Intl", "city": "Ulaanbaatar", "country_iso": "MNG", "lat": 47.8431, "lon": 106.7672, "elevation_ft": 4364, "airport_type": "large_airport", "pax_annual": 1.8, "runways": 1, "continent": "AS"},
    {"iata": "DYU", "icao": "UTDD", "name": "Dushanbe Intl", "city": "Dushanbe", "country_iso": "TJK", "lat": 38.5433, "lon": 68.8250, "elevation_ft": 2575, "airport_type": "medium_airport", "pax_annual": 1.5, "runways": 1, "continent": "AS"},
    {"iata": "ASB", "icao": "UTAA", "name": "Ashgabat Intl", "city": "Ashgabat", "country_iso": "TKM", "lat": 37.9868, "lon": 58.3610, "elevation_ft": 692, "airport_type": "large_airport", "pax_annual": 1.5, "runways": 1, "continent": "AS"},

    # ── Europe (expansion) ──
    {"iata": "KBP", "icao": "UKBB", "name": "Boryspil Intl", "city": "Kyiv", "country_iso": "UKR", "lat": 50.3450, "lon": 30.8947, "elevation_ft": 427, "airport_type": "large_airport", "pax_annual": 15.3, "runways": 2, "continent": "EU"},
    {"iata": "VNO", "icao": "EYVI", "name": "Vilnius Intl", "city": "Vilnius", "country_iso": "LTU", "lat": 54.6341, "lon": 25.2858, "elevation_ft": 646, "airport_type": "large_airport", "pax_annual": 6.2, "runways": 1, "continent": "EU"},
    {"iata": "MSQ", "icao": "UMMS", "name": "Minsk National Airport", "city": "Minsk", "country_iso": "BLR", "lat": 53.8825, "lon": 28.0307, "elevation_ft": 670, "airport_type": "large_airport", "pax_annual": 5.0, "runways": 1, "continent": "EU"},
    {"iata": "TIA", "icao": "LATI", "name": "Tirana Mother Teresa Intl", "city": "Tirana", "country_iso": "ALB", "lat": 41.4147, "lon": 19.7206, "elevation_ft": 126, "airport_type": "large_airport", "pax_annual": 3.5, "runways": 1, "continent": "EU"},
    {"iata": "TLL", "icao": "EETN", "name": "Tallinn Lennart Meri", "city": "Tallinn", "country_iso": "EST", "lat": 59.4133, "lon": 24.8328, "elevation_ft": 131, "airport_type": "large_airport", "pax_annual": 3.3, "runways": 1, "continent": "EU"},
    {"iata": "SKP", "icao": "LWSK", "name": "Skopje Intl", "city": "Skopje", "country_iso": "MKD", "lat": 41.9617, "lon": 21.6214, "elevation_ft": 781, "airport_type": "medium_airport", "pax_annual": 2.5, "runways": 1, "continent": "EU"},
    {"iata": "KIV", "icao": "LUKK", "name": "Chisinau Intl", "city": "Chisinau", "country_iso": "MDA", "lat": 46.9277, "lon": 28.9310, "elevation_ft": 399, "airport_type": "medium_airport", "pax_annual": 2.5, "runways": 1, "continent": "EU"},
    {"iata": "LJU", "icao": "LJLJ", "name": "Ljubljana Joze Pucnik", "city": "Ljubljana", "country_iso": "SVN", "lat": 46.2237, "lon": 14.4576, "elevation_ft": 1273, "airport_type": "medium_airport", "pax_annual": 1.8, "runways": 1, "continent": "EU"},
    {"iata": "SJJ", "icao": "LQSA", "name": "Sarajevo Intl", "city": "Sarajevo", "country_iso": "BIH", "lat": 43.8246, "lon": 18.3315, "elevation_ft": 1708, "airport_type": "medium_airport", "pax_annual": 1.1, "runways": 1, "continent": "EU"},

    # ── North America – Caribbean & Central America (expansion) ──
    {"iata": "SDQ", "icao": "MDSD", "name": "Las Americas Intl", "city": "Santo Domingo", "country_iso": "DOM", "lat": 18.4297, "lon": -69.6689, "elevation_ft": 59, "airport_type": "large_airport", "pax_annual": 6.5, "runways": 2, "continent": "NA"},
    {"iata": "HAV", "icao": "MUHA", "name": "Jose Marti Intl", "city": "Havana", "country_iso": "CUB", "lat": 22.9892, "lon": -82.4092, "elevation_ft": 210, "airport_type": "large_airport", "pax_annual": 4.5, "runways": 2, "continent": "NA"},
    {"iata": "NAS", "icao": "MYNN", "name": "Lynden Pindling Intl", "city": "Nassau", "country_iso": "BHS", "lat": 25.0390, "lon": -77.4662, "elevation_ft": 16, "airport_type": "large_airport", "pax_annual": 3.8, "runways": 2, "continent": "NA"},
    {"iata": "GUA", "icao": "MGGT", "name": "La Aurora Intl", "city": "Guatemala City", "country_iso": "GTM", "lat": 14.5833, "lon": -90.5275, "elevation_ft": 4952, "airport_type": "large_airport", "pax_annual": 3.3, "runways": 1, "continent": "NA"},
    {"iata": "SAL", "icao": "MSLP", "name": "Monsenor Oscar Arnulfo Romero Intl", "city": "San Salvador", "country_iso": "SLV", "lat": 13.4409, "lon": -89.0557, "elevation_ft": 101, "airport_type": "large_airport", "pax_annual": 2.8, "runways": 1, "continent": "NA"},
    {"iata": "KIN", "icao": "MKJP", "name": "Norman Manley Intl", "city": "Kingston", "country_iso": "JAM", "lat": 17.9357, "lon": -76.7875, "elevation_ft": 10, "airport_type": "large_airport", "pax_annual": 2.5, "runways": 1, "continent": "NA"},
    {"iata": "MGA", "icao": "MNMG", "name": "Augusto C. Sandino Intl", "city": "Managua", "country_iso": "NIC", "lat": 12.1415, "lon": -86.1682, "elevation_ft": 194, "airport_type": "large_airport", "pax_annual": 1.6, "runways": 1, "continent": "NA"},
    {"iata": "TGU", "icao": "MHTG", "name": "Toncontin Intl", "city": "Tegucigalpa", "country_iso": "HND", "lat": 14.0609, "lon": -87.2172, "elevation_ft": 3294, "airport_type": "medium_airport", "pax_annual": 1.5, "runways": 1, "continent": "NA"},
    {"iata": "BDA", "icao": "TXKF", "name": "L.F. Wade Intl", "city": "Hamilton", "country_iso": "BMU", "lat": 32.3640, "lon": -64.6787, "elevation_ft": 12, "airport_type": "medium_airport", "pax_annual": 0.9, "runways": 1, "continent": "NA"},
    {"iata": "POS", "icao": "TTPP", "name": "Piarco Intl", "city": "Port of Spain", "country_iso": "TTO", "lat": 10.5954, "lon": -61.3372, "elevation_ft": 58, "airport_type": "large_airport", "pax_annual": 3.5, "runways": 2, "continent": "NA"},
    {"iata": "BGI", "icao": "TBPB", "name": "Grantley Adams Intl", "city": "Bridgetown", "country_iso": "BRB", "lat": 13.0746, "lon": -59.4925, "elevation_ft": 169, "airport_type": "large_airport", "pax_annual": 2.5, "runways": 1, "continent": "NA"},
    {"iata": "AUA", "icao": "TNCA", "name": "Queen Beatrix Intl", "city": "Oranjestad", "country_iso": "ABW", "lat": 12.5014, "lon": -70.0152, "elevation_ft": 60, "airport_type": "large_airport", "pax_annual": 2.5, "runways": 1, "continent": "NA"},
    {"iata": "CUR", "icao": "TNCC", "name": "Hato Intl", "city": "Willemstad", "country_iso": "CUW", "lat": 12.1889, "lon": -68.9598, "elevation_ft": 29, "airport_type": "large_airport", "pax_annual": 2.2, "runways": 1, "continent": "NA"},
    {"iata": "BZE", "icao": "MZBZ", "name": "Philip Goldson Intl", "city": "Belize City", "country_iso": "BLZ", "lat": 17.5391, "lon": -88.3082, "elevation_ft": 15, "airport_type": "medium_airport", "pax_annual": 1.1, "runways": 1, "continent": "NA"},
    {"iata": "GCM", "icao": "MWCR", "name": "Owen Roberts Intl", "city": "George Town", "country_iso": "CYM", "lat": 19.2928, "lon": -81.3577, "elevation_ft": 8, "airport_type": "medium_airport", "pax_annual": 2.0, "runways": 1, "continent": "NA"},

    # ── Africa (round 2) ──
    {"iata": "KRT", "icao": "HSSS", "name": "Khartoum Intl", "city": "Khartoum", "country_iso": "SDN", "lat": 15.5895, "lon": 32.5532, "elevation_ft": 1265, "airport_type": "large_airport", "pax_annual": 3.0, "runways": 2, "continent": "AF"},
    {"iata": "TIP", "icao": "HLLT", "name": "Mitiga Intl", "city": "Tripoli", "country_iso": "LBY", "lat": 32.8941, "lon": 13.2760, "elevation_ft": 36, "airport_type": "large_airport", "pax_annual": 2.0, "runways": 1, "continent": "AF"},
    {"iata": "RAK", "icao": "GMMX", "name": "Marrakech Menara", "city": "Marrakech", "country_iso": "MAR", "lat": 31.6069, "lon": -8.0363, "elevation_ft": 1545, "airport_type": "large_airport", "pax_annual": 6.0, "runways": 1, "continent": "AF"},
    {"iata": "HRG", "icao": "HEGN", "name": "Hurghada Intl", "city": "Hurghada", "country_iso": "EGY", "lat": 27.1784, "lon": 33.7994, "elevation_ft": 52, "airport_type": "large_airport", "pax_annual": 7.5, "runways": 1, "continent": "AF"},
    {"iata": "SSH", "icao": "HESH", "name": "Sharm El Sheikh Intl", "city": "Sharm El Sheikh", "country_iso": "EGY", "lat": 27.9773, "lon": 34.3950, "elevation_ft": 143, "airport_type": "large_airport", "pax_annual": 5.0, "runways": 1, "continent": "AF"},
    {"iata": "MBA", "icao": "HKMO", "name": "Moi Intl", "city": "Mombasa", "country_iso": "KEN", "lat": -4.0348, "lon": 39.5942, "elevation_ft": 200, "airport_type": "large_airport", "pax_annual": 1.8, "runways": 1, "continent": "AF"},
    {"iata": "DUR", "icao": "FALE", "name": "King Shaka Intl", "city": "Durban", "country_iso": "ZAF", "lat": -29.6144, "lon": 31.1197, "elevation_ft": 295, "airport_type": "large_airport", "pax_annual": 5.8, "runways": 1, "continent": "AF"},
    {"iata": "BKO", "icao": "GABS", "name": "Bamako-Senou Intl", "city": "Bamako", "country_iso": "MLI", "lat": 12.5335, "lon": -7.9499, "elevation_ft": 1247, "airport_type": "large_airport", "pax_annual": 1.3, "runways": 1, "continent": "AF"},
    {"iata": "OUA", "icao": "DFFD", "name": "Thomas Sankara Intl", "city": "Ouagadougou", "country_iso": "BFA", "lat": 12.3532, "lon": -1.5124, "elevation_ft": 1037, "airport_type": "large_airport", "pax_annual": 0.8, "runways": 1, "continent": "AF"},
    {"iata": "NIM", "icao": "DRRN", "name": "Diori Hamani Intl", "city": "Niamey", "country_iso": "NER", "lat": 13.4815, "lon": 2.1836, "elevation_ft": 732, "airport_type": "medium_airport", "pax_annual": 0.4, "runways": 1, "continent": "AF"},
    {"iata": "NDJ", "icao": "FTTJ", "name": "N Djamena Hassan Djamous Intl", "city": "N Djamena", "country_iso": "TCD", "lat": 12.1337, "lon": 15.0340, "elevation_ft": 968, "airport_type": "medium_airport", "pax_annual": 0.4, "runways": 1, "continent": "AF"},
    {"iata": "CKY", "icao": "GUCY", "name": "Conakry Intl", "city": "Conakry", "country_iso": "GIN", "lat": 9.5769, "lon": -13.6120, "elevation_ft": 72, "airport_type": "medium_airport", "pax_annual": 0.5, "runways": 1, "continent": "AF"},
    {"iata": "LFW", "icao": "DXXX", "name": "Lome-Tokoin Gnassingbe Eyadema Intl", "city": "Lome", "country_iso": "TGO", "lat": 6.1661, "lon": 1.2545, "elevation_ft": 72, "airport_type": "medium_airport", "pax_annual": 0.7, "runways": 1, "continent": "AF"},
    {"iata": "COO", "icao": "DBBB", "name": "Cadjehoun", "city": "Cotonou", "country_iso": "BEN", "lat": 6.3573, "lon": 2.3845, "elevation_ft": 19, "airport_type": "medium_airport", "pax_annual": 0.5, "runways": 1, "continent": "AF"},
    {"iata": "LBV", "icao": "FOOL", "name": "Leon Mba Intl", "city": "Libreville", "country_iso": "GAB", "lat": 0.4586, "lon": 9.4123, "elevation_ft": 39, "airport_type": "large_airport", "pax_annual": 0.7, "runways": 1, "continent": "AF"},
    {"iata": "BZV", "icao": "FCBB", "name": "Maya-Maya", "city": "Brazzaville", "country_iso": "COG", "lat": -4.2517, "lon": 15.2530, "elevation_ft": 1048, "airport_type": "medium_airport", "pax_annual": 0.5, "runways": 1, "continent": "AF"},
    {"iata": "SSG", "icao": "FGSL", "name": "Malabo Intl", "city": "Malabo", "country_iso": "GNQ", "lat": 3.7553, "lon": 8.7087, "elevation_ft": 76, "airport_type": "medium_airport", "pax_annual": 0.3, "runways": 1, "continent": "AF"},
    {"iata": "FNA", "icao": "GFLL", "name": "Lungi Intl", "city": "Freetown", "country_iso": "SLE", "lat": 8.6164, "lon": -13.1956, "elevation_ft": 84, "airport_type": "medium_airport", "pax_annual": 0.3, "runways": 1, "continent": "AF"},
    {"iata": "ROB", "icao": "GLRB", "name": "Roberts Intl", "city": "Monrovia", "country_iso": "LBR", "lat": 6.2338, "lon": -10.3623, "elevation_ft": 31, "airport_type": "medium_airport", "pax_annual": 0.2, "runways": 1, "continent": "AF"},
    {"iata": "BGF", "icao": "FEFF", "name": "Bangui M Poko Intl", "city": "Bangui", "country_iso": "CAF", "lat": 4.3985, "lon": 18.5188, "elevation_ft": 1208, "airport_type": "medium_airport", "pax_annual": 0.1, "runways": 1, "continent": "AF"},
    {"iata": "JUB", "icao": "HSSJ", "name": "Juba Intl", "city": "Juba", "country_iso": "SSD", "lat": 4.8721, "lon": 31.6011, "elevation_ft": 1513, "airport_type": "medium_airport", "pax_annual": 0.3, "runways": 1, "continent": "AF"},
    {"iata": "MGQ", "icao": "HCMM", "name": "Aden Abdulle Intl", "city": "Mogadishu", "country_iso": "SOM", "lat": 2.0144, "lon": 45.3047, "elevation_ft": 29, "airport_type": "medium_airport", "pax_annual": 0.5, "runways": 1, "continent": "AF"},
    {"iata": "JIB", "icao": "HDAM", "name": "Djibouti-Ambouli Intl", "city": "Djibouti", "country_iso": "DJI", "lat": 11.5473, "lon": 43.1595, "elevation_ft": 49, "airport_type": "medium_airport", "pax_annual": 0.4, "runways": 1, "continent": "AF"},
    {"iata": "ASM", "icao": "HHAS", "name": "Asmara Intl", "city": "Asmara", "country_iso": "ERI", "lat": 15.2919, "lon": 38.9107, "elevation_ft": 7661, "airport_type": "medium_airport", "pax_annual": 0.2, "runways": 1, "continent": "AF"},
    {"iata": "GBE", "icao": "FBSK", "name": "Sir Seretse Khama Intl", "city": "Gaborone", "country_iso": "BWA", "lat": -24.5552, "lon": 25.9182, "elevation_ft": 3299, "airport_type": "medium_airport", "pax_annual": 0.5, "runways": 1, "continent": "AF"},
    {"iata": "NKC", "icao": "GQNO", "name": "Oumtounsy Intl", "city": "Nouakchott", "country_iso": "MRT", "lat": 18.3101, "lon": -15.9697, "elevation_ft": 13, "airport_type": "medium_airport", "pax_annual": 0.3, "runways": 1, "continent": "AF"},
    {"iata": "SID", "icao": "GVAC", "name": "Amilcar Cabral Intl", "city": "Sal", "country_iso": "CPV", "lat": 16.7414, "lon": -22.9494, "elevation_ft": 177, "airport_type": "large_airport", "pax_annual": 1.5, "runways": 1, "continent": "AF"},

    # ── Asia (round 2) ──
    {"iata": "BEY", "icao": "OLBA", "name": "Rafic Hariri Intl", "city": "Beirut", "country_iso": "LBN", "lat": 33.8209, "lon": 35.4884, "elevation_ft": 87, "airport_type": "large_airport", "pax_annual": 8.8, "runways": 1, "continent": "AS"},
    {"iata": "DPS", "icao": "WADD", "name": "Ngurah Rai Intl", "city": "Bali", "country_iso": "IDN", "lat": -8.7482, "lon": 115.1672, "elevation_ft": 14, "airport_type": "large_airport", "pax_annual": 24.0, "runways": 1, "continent": "AS"},
    {"iata": "SUB", "icao": "WARR", "name": "Juanda Intl", "city": "Surabaya", "country_iso": "IDN", "lat": -7.3798, "lon": 112.7868, "elevation_ft": 9, "airport_type": "large_airport", "pax_annual": 18.0, "runways": 1, "continent": "AS"},
    {"iata": "KNO", "icao": "WIMM", "name": "Kualanamu Intl", "city": "Medan", "country_iso": "IDN", "lat": 3.6422, "lon": 98.8853, "elevation_ft": 79, "airport_type": "large_airport", "pax_annual": 10.0, "runways": 1, "continent": "AS"},
    {"iata": "HKT", "icao": "VTSP", "name": "Phuket Intl", "city": "Phuket", "country_iso": "THA", "lat": 8.1132, "lon": 98.3169, "elevation_ft": 82, "airport_type": "large_airport", "pax_annual": 18.0, "runways": 1, "continent": "AS"},
    {"iata": "CNX", "icao": "VTCC", "name": "Chiang Mai Intl", "city": "Chiang Mai", "country_iso": "THA", "lat": 18.7668, "lon": 98.9626, "elevation_ft": 1036, "airport_type": "large_airport", "pax_annual": 10.5, "runways": 1, "continent": "AS"},
    {"iata": "DAD", "icao": "VVDN", "name": "Da Nang Intl", "city": "Da Nang", "country_iso": "VNM", "lat": 16.0439, "lon": 108.1994, "elevation_ft": 33, "airport_type": "large_airport", "pax_annual": 15.5, "runways": 1, "continent": "AS"},
    {"iata": "NGO", "icao": "RJGG", "name": "Chubu Centrair Intl", "city": "Nagoya", "country_iso": "JPN", "lat": 34.8584, "lon": 136.8127, "elevation_ft": 15, "airport_type": "large_airport", "pax_annual": 13.1, "runways": 1, "continent": "AS"},
    {"iata": "CJU", "icao": "RKPC", "name": "Jeju Intl", "city": "Jeju", "country_iso": "KOR", "lat": 33.5113, "lon": 126.4930, "elevation_ft": 118, "airport_type": "large_airport", "pax_annual": 29.5, "runways": 2, "continent": "AS"},
    {"iata": "KHI", "icao": "OPKC", "name": "Jinnah Intl", "city": "Karachi", "country_iso": "PAK", "lat": 24.9065, "lon": 67.1609, "elevation_ft": 100, "airport_type": "large_airport", "pax_annual": 8.5, "runways": 2, "continent": "AS"},
    {"iata": "LHE", "icao": "OPLA", "name": "Allama Iqbal Intl", "city": "Lahore", "country_iso": "PAK", "lat": 31.5216, "lon": 74.4036, "elevation_ft": 712, "airport_type": "large_airport", "pax_annual": 7.0, "runways": 2, "continent": "AS"},
    {"iata": "AMD", "icao": "VAAH", "name": "Sardar Vallabhbhai Patel Intl", "city": "Ahmedabad", "country_iso": "IND", "lat": 23.0772, "lon": 72.6347, "elevation_ft": 189, "airport_type": "large_airport", "pax_annual": 12.0, "runways": 1, "continent": "AS"},
    {"iata": "COK", "icao": "VOCI", "name": "Cochin Intl", "city": "Kochi", "country_iso": "IND", "lat": 10.1520, "lon": 76.4019, "elevation_ft": 30, "airport_type": "large_airport", "pax_annual": 10.2, "runways": 1, "continent": "AS"},
    {"iata": "GOI", "icao": "VOGO", "name": "Goa Intl (Dabolim)", "city": "Goa", "country_iso": "IND", "lat": 15.3808, "lon": 73.8314, "elevation_ft": 186, "airport_type": "large_airport", "pax_annual": 8.5, "runways": 1, "continent": "AS"},
    {"iata": "WUH", "icao": "ZHHH", "name": "Wuhan Tianhe Intl", "city": "Wuhan", "country_iso": "CHN", "lat": 30.7838, "lon": 114.2081, "elevation_ft": 113, "airport_type": "large_airport", "pax_annual": 27.2, "runways": 2, "continent": "AS"},
    {"iata": "NKG", "icao": "ZSNJ", "name": "Nanjing Lukou Intl", "city": "Nanjing", "country_iso": "CHN", "lat": 31.7420, "lon": 118.8620, "elevation_ft": 49, "airport_type": "large_airport", "pax_annual": 30.0, "runways": 2, "continent": "AS"},
    {"iata": "XMN", "icao": "ZSAM", "name": "Xiamen Gaoqi Intl", "city": "Xiamen", "country_iso": "CHN", "lat": 24.5440, "lon": 118.1278, "elevation_ft": 59, "airport_type": "large_airport", "pax_annual": 27.3, "runways": 1, "continent": "AS"},
    {"iata": "PEN", "icao": "WMKP", "name": "Penang Intl", "city": "Penang", "country_iso": "MYS", "lat": 5.2971, "lon": 100.2767, "elevation_ft": 11, "airport_type": "large_airport", "pax_annual": 7.8, "runways": 1, "continent": "AS"},
    {"iata": "BKI", "icao": "WBKK", "name": "Kota Kinabalu Intl", "city": "Kota Kinabalu", "country_iso": "MYS", "lat": 5.9372, "lon": 116.0515, "elevation_ft": 10, "airport_type": "large_airport", "pax_annual": 8.5, "runways": 1, "continent": "AS"},
    {"iata": "BWN", "icao": "WBSB", "name": "Brunei Intl", "city": "Bandar Seri Begawan", "country_iso": "BRN", "lat": 4.9442, "lon": 114.9283, "elevation_ft": 73, "airport_type": "large_airport", "pax_annual": 1.8, "runways": 1, "continent": "AS"},
    {"iata": "MFM", "icao": "VMMC", "name": "Macau Intl", "city": "Macau", "country_iso": "CHN", "lat": 22.1496, "lon": 113.5920, "elevation_ft": 20, "airport_type": "large_airport", "pax_annual": 9.3, "runways": 1, "continent": "AS"},

    # ── Europe (round 2) ──
    {"iata": "LCA", "icao": "LCLK", "name": "Larnaca Intl", "city": "Larnaca", "country_iso": "CYP", "lat": 34.8754, "lon": 33.6249, "elevation_ft": 8, "airport_type": "large_airport", "pax_annual": 11.0, "runways": 1, "continent": "EU"},
    {"iata": "MLA", "icao": "LMML", "name": "Malta Intl", "city": "Luqa", "country_iso": "MLT", "lat": 35.8575, "lon": 14.4775, "elevation_ft": 300, "airport_type": "large_airport", "pax_annual": 7.3, "runways": 1, "continent": "EU"},
    {"iata": "LUX", "icao": "ELLX", "name": "Luxembourg-Findel Intl", "city": "Luxembourg", "country_iso": "LUX", "lat": 49.6233, "lon": 6.2044, "elevation_ft": 1234, "airport_type": "large_airport", "pax_annual": 4.8, "runways": 1, "continent": "EU"},
    {"iata": "TGD", "icao": "LYPG", "name": "Podgorica", "city": "Podgorica", "country_iso": "MNE", "lat": 42.3594, "lon": 19.2519, "elevation_ft": 141, "airport_type": "medium_airport", "pax_annual": 2.5, "runways": 1, "continent": "EU"},
    {"iata": "PRN", "icao": "BKPR", "name": "Pristina Intl Adem Jashari", "city": "Pristina", "country_iso": "XKX", "lat": 42.5728, "lon": 21.0358, "elevation_ft": 1789, "airport_type": "medium_airport", "pax_annual": 2.3, "runways": 1, "continent": "EU"},
    {"iata": "STR", "icao": "EDDS", "name": "Stuttgart", "city": "Stuttgart", "country_iso": "DEU", "lat": 48.6899, "lon": 9.2220, "elevation_ft": 1276, "airport_type": "large_airport", "pax_annual": 12.7, "runways": 1, "continent": "EU"},
    {"iata": "CGN", "icao": "EDDK", "name": "Cologne Bonn", "city": "Cologne", "country_iso": "DEU", "lat": 50.8659, "lon": 7.1427, "elevation_ft": 302, "airport_type": "large_airport", "pax_annual": 12.4, "runways": 3, "continent": "EU"},
    {"iata": "GDN", "icao": "EPGD", "name": "Gdansk Lech Walesa", "city": "Gdansk", "country_iso": "POL", "lat": 54.3776, "lon": 18.4662, "elevation_ft": 489, "airport_type": "large_airport", "pax_annual": 5.4, "runways": 1, "continent": "EU"},
    {"iata": "KRK", "icao": "EPKK", "name": "Krakow John Paul II Intl", "city": "Krakow", "country_iso": "POL", "lat": 50.0777, "lon": 19.7848, "elevation_ft": 791, "airport_type": "large_airport", "pax_annual": 9.4, "runways": 1, "continent": "EU"},
    {"iata": "OPO", "icao": "LPPR", "name": "Porto Francisco Sa Carneiro", "city": "Porto", "country_iso": "PRT", "lat": 41.2481, "lon": -8.6814, "elevation_ft": 228, "airport_type": "large_airport", "pax_annual": 13.1, "runways": 1, "continent": "EU"},
    {"iata": "FAO", "icao": "LPFR", "name": "Faro", "city": "Faro", "country_iso": "PRT", "lat": 37.0144, "lon": -7.9659, "elevation_ft": 24, "airport_type": "large_airport", "pax_annual": 9.0, "runways": 1, "continent": "EU"},
    {"iata": "CLJ", "icao": "LRCL", "name": "Cluj-Napoca Intl", "city": "Cluj-Napoca", "country_iso": "ROU", "lat": 46.7852, "lon": 23.6862, "elevation_ft": 1036, "airport_type": "large_airport", "pax_annual": 2.9, "runways": 1, "continent": "EU"},
    {"iata": "SKG", "icao": "LGTS", "name": "Thessaloniki Macedonia Intl", "city": "Thessaloniki", "country_iso": "GRC", "lat": 40.5197, "lon": 22.9709, "elevation_ft": 22, "airport_type": "large_airport", "pax_annual": 8.0, "runways": 1, "continent": "EU"},
    {"iata": "VKO", "icao": "UUWW", "name": "Moscow Vnukovo", "city": "Moscow", "country_iso": "RUS", "lat": 55.5961, "lon": 37.2615, "elevation_ft": 685, "airport_type": "large_airport", "pax_annual": 21.3, "runways": 2, "continent": "EU"},

    # ── Oceania (round 2) ──
    {"iata": "CBR", "icao": "YSCB", "name": "Canberra", "city": "Canberra", "country_iso": "AUS", "lat": -35.3069, "lon": 149.1950, "elevation_ft": 1886, "airport_type": "large_airport", "pax_annual": 3.2, "runways": 1, "continent": "OC"},
    {"iata": "DRW", "icao": "YPDN", "name": "Darwin Intl", "city": "Darwin", "country_iso": "AUS", "lat": -12.4147, "lon": 130.8772, "elevation_ft": 103, "airport_type": "large_airport", "pax_annual": 2.5, "runways": 1, "continent": "OC"},
    {"iata": "HBA", "icao": "YMHB", "name": "Hobart Intl", "city": "Hobart", "country_iso": "AUS", "lat": -42.8361, "lon": 147.5103, "elevation_ft": 13, "airport_type": "large_airport", "pax_annual": 2.8, "runways": 1, "continent": "OC"},
    {"iata": "GUM", "icao": "PGUM", "name": "Antonio B. Won Pat Intl", "city": "Hagatna", "country_iso": "GUM", "lat": 13.4834, "lon": 144.7961, "elevation_ft": 298, "airport_type": "large_airport", "pax_annual": 3.5, "runways": 2, "continent": "OC"},
    {"iata": "NOU", "icao": "NWWW", "name": "La Tontouta Intl", "city": "Noumea", "country_iso": "NCL", "lat": -22.0146, "lon": 166.2128, "elevation_ft": 52, "airport_type": "medium_airport", "pax_annual": 0.8, "runways": 1, "continent": "OC"},
    {"iata": "VLI", "icao": "NVVV", "name": "Bauerfield Intl", "city": "Port Vila", "country_iso": "VUT", "lat": -17.6993, "lon": 168.3200, "elevation_ft": 70, "airport_type": "medium_airport", "pax_annual": 0.3, "runways": 1, "continent": "OC"},
    {"iata": "HIR", "icao": "AGGH", "name": "Honiara Intl", "city": "Honiara", "country_iso": "SLB", "lat": -9.4280, "lon": 160.0549, "elevation_ft": 28, "airport_type": "medium_airport", "pax_annual": 0.4, "runways": 1, "continent": "OC"},
    {"iata": "APW", "icao": "NSFA", "name": "Faleolo Intl", "city": "Apia", "country_iso": "WSM", "lat": -13.8297, "lon": -172.0083, "elevation_ft": 58, "airport_type": "medium_airport", "pax_annual": 0.3, "runways": 1, "continent": "OC"},

    # ── South America (round 2) ──
    {"iata": "CTG", "icao": "SKCG", "name": "Rafael Nunez Intl", "city": "Cartagena", "country_iso": "COL", "lat": 10.4424, "lon": -75.5130, "elevation_ft": 2, "airport_type": "large_airport", "pax_annual": 6.5, "runways": 1, "continent": "SA"},
    {"iata": "CLO", "icao": "SKCL", "name": "Alfonso Bonilla Aragon Intl", "city": "Cali", "country_iso": "COL", "lat": 3.5432, "lon": -76.3816, "elevation_ft": 3162, "airport_type": "large_airport", "pax_annual": 5.0, "runways": 1, "continent": "SA"},
    {"iata": "AEP", "icao": "SABE", "name": "Aeroparque Jorge Newbery", "city": "Buenos Aires", "country_iso": "ARG", "lat": -34.5592, "lon": -58.4156, "elevation_ft": 18, "airport_type": "large_airport", "pax_annual": 12.5, "runways": 1, "continent": "SA"},
    {"iata": "COR", "icao": "SACO", "name": "Ingeniero Ambrosio Taravella Intl", "city": "Cordoba", "country_iso": "ARG", "lat": -31.3236, "lon": -64.2078, "elevation_ft": 1604, "airport_type": "large_airport", "pax_annual": 3.5, "runways": 1, "continent": "SA"},
    {"iata": "MDZ", "icao": "SAME", "name": "El Plumerillo Intl", "city": "Mendoza", "country_iso": "ARG", "lat": -32.8317, "lon": -68.7929, "elevation_ft": 2310, "airport_type": "large_airport", "pax_annual": 1.8, "runways": 1, "continent": "SA"},
    {"iata": "GEO", "icao": "SYCJ", "name": "Cheddi Jagan Intl", "city": "Georgetown", "country_iso": "GUY", "lat": 6.4985, "lon": -58.2541, "elevation_ft": 95, "airport_type": "large_airport", "pax_annual": 0.5, "runways": 1, "continent": "SA"},
    {"iata": "PBM", "icao": "SMJP", "name": "Johan Adolf Pengel Intl", "city": "Paramaribo", "country_iso": "SUR", "lat": 5.4528, "lon": -55.1879, "elevation_ft": 59, "airport_type": "medium_airport", "pax_annual": 0.5, "runways": 1, "continent": "SA"},
    {"iata": "LPB", "icao": "SLLP", "name": "El Alto Intl", "city": "La Paz", "country_iso": "BOL", "lat": -16.5133, "lon": -68.1923, "elevation_ft": 13325, "airport_type": "large_airport", "pax_annual": 2.5, "runways": 1, "continent": "SA"},
]


def seed_airports():
    """Seed airport data into the database."""
    db = SessionLocal()

    try:
        for airport_data in AIRPORTS_DATA:
            existing = db.query(Airport).filter(Airport.iata == airport_data["iata"]).first()

            if existing:
                for key, value in airport_data.items():
                    setattr(existing, key, value)
            else:
                airport = Airport(**airport_data)
                db.add(airport)

        db.commit()
        logger.info(f"Seeded {len(AIRPORTS_DATA)} airports")

    finally:
        db.close()

    return len(AIRPORTS_DATA)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    seed_airports()
